version: "3"

services:

	nginx:
		image: nginx
		ports:
		- '8080:80'
		volumes: 
		- ./:/Evaluation-Docker
		- ./site.conf:/etc/nginx/conf.d/default.conf
		links:
		- php
	php:
		image: php:7.1-fpm
		volumes: 
		- ./:/Evaluation-Docker

	jenkins:
		image: jenkins/jenkins
		build: .
		restart: unless-stopped
		ports:
		- 's:8080'
		volumes:
		- ./jenkins:/var/jenkins_home
